### ISSUE TITLE
[0.8.0] Scales shows as offline.

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#515]
Hello,
My scales instance shows offline in the panel, even though it is running. Ports are open, and scales is running. I have no idea what is going on. **Could using an IP for the FQDN and IP be a problem?**
[root@s1 scales]# npm start

> Scales@0.1.0 start /srv/scales
> forever start lib/scales.js

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: lib/scales.js

**Comment by DaneEveritt** [comment]
Can you access https://whatever.yourip.com:5656 in your browser?

**Comment by Dylan3304** [comment]
@DaneEveritt it returns `"Scales management daemon"`

**Comment by DaneEveritt** [comment]
Possible duplicate of #504, but I need more specific information about where the error is occurring.

Can you also provide logs from `src/logs/info.log` and `exception.log` (if there is anything in that one that is relevant).

**Comment by Dylan3304** [comment]
@DaneEveritt it shows as offline in the panel. 
**Info Log:** [2015-04-29 20-24-34] Exception: Peer's certificate issuer has been marked as not trusted by the user. in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/mashape/unirest-php/src/Unirest/Request.php:427  @  http://cp.minewrath.com/admin/server/new  @@  exception-2015-04-29-20-24-34-0b00e688b4c923ba69c00b2a891e0265.html

**Exception Log:** [2015-04-29 20-05-28] Klein\Exceptions\UnhandledException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/klein/klein/src/Klein/Klein.php:925 caused by PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/j4mie/idiorm/idiorm.php:429  @  http://cp.minewrath.com/admin/node/view/1/settings  @@  exception-2015-04-29-20-05-28-64274d4ac3bc16ee6ddd4c32099ee94c.html
[2015-04-29 20-05-33] Klein\Exceptions\UnhandledException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/klein/klein/src/Klein/Klein.php:925 caused by PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/j4mie/idiorm/idiorm.php:429  @  http://cp.minewrath.com/admin/node/view/1/settings  @@  exception-2015-04-29-20-05-28-64274d4ac3bc16ee6ddd4c32099ee94c.html

**Comment by DaneEveritt** [comment]
It appears that you have an issue with your SSL certificate. `Peer's certificate issuer has been marked as not trusted by the user.`

Those errors in the exception log appear to be something else that we need to look into.

**Comment by Dylan3304** [comment]
Okay, any ideas?

**Comment by DaneEveritt** [comment]
So the biggest problem with using SSL certificates and IPs is that it doesn't work well. I would suggest setting up a subdomain to point to your Scales instance IP which you can use when making the SSL certificate. When you are running that command there is a point at which you reach the following:

`Common Name (eg, your name or your server's hostname) []:`

You can try putting your IP there and see if that works, if not you probably need to use a domain there.

**Comment by Dylan3304** [comment]
@DaneEveritt Okay, It doesn't let me use a subdomain, `The node Fully Qualified Domain Name is not valid. Domains must resolve to a non-reserved IP.`
I only have one IP.

**Comment by DaneEveritt** [comment]
You are probably entering something wrong. Make sure you enter `node.example.com` or similar, don't include `www.` or `http://`. Also make sure that it is a real domain.

**Comment by Dylan3304** [comment]
@DaneEveritt SSL didn't help. I tried to use `s1.minewrath.com`, which resolves to `167.114.159.112`. Same error.

**Comment by DaneEveritt** [comment]
Did you update your certificate? You need to make a new one to match that domain.

**Comment by Dylan3304** [comment]
@DaneEveritt yes.

**Comment by DaneEveritt** [comment]
Try using a certificate from https://www.startssl.com and see if it fixes and problems.

**Comment by Dylan3304** [comment]
@DaneEveritt that is a bit of a hassle. Anything else I could try, like force changing it in PHPMyAdmin?

**Comment by DaneEveritt** [comment]
There isn't anything we can do to fix an invalid SSL certificate, it isn't working because the libraries can't validate the certificate, and even ignoring errors doesn't fix this.

**Comment by Dylan3304** [comment]
@DaneEveritt just curious, what directory do I make the SSLs in?

**Comment by DaneEveritt** [comment]
Hang on, currently investigating a possible issue that is causing this error.

**Comment by Dylan3304** [comment]
Yey! @DaneEveritt. I'll be waiting!

**Comment by DaneEveritt** [comment]
Can you name something in the panel that is saying Scales is offline for me?

**Comment by Dylan3304** [comment]
@DaneEveritt the red indicator light.

**Comment by DaneEveritt** [comment]
Can you add the line below above [this line](https://github.com/PufferPanel/PufferPanel/blob/master/src/core/components/daemon.php#L37) for me and tell me what happens?

```
Unirest\Request::verifyPeer(false);
```

**Comment by Dylan3304** [comment]
@DaneEveritt added, restarted scales also. Didn't do anything.

**daemon.php:**
<?php
/*
PufferPanel - A Minecraft Server Management Panel
Copyright (c) 2013 Dane Everitt

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.
*/
namespace PufferPanel\Core\Components;
use \Unirest;

/**
* General Functions Trait
*/
trait Daemon {

	/**
	 * Checks if the daemon is running.
	 *
	 * @param string $ip
	 * @param int $port
	 * @param int $timeout
	 * @return bool
	 */
	public function avaliable($ip, $port = 5656, $timeout = 3) {
		
		Unirest\Request::verifyPeer(false);
		
		Unirest\Request::timeout($timeout);

		try {

			Unirest\Request::get("https://".$ip.":".$port);
			return true;

		} catch(\Exception $e) {
			return false;
		}

	}

}

?>

**Comment by DaneEveritt** [comment]
Ok, sounds like it is an issue with your SSL certificate that can't even be overridden in the program. Let me know if using a StartSSL certificate fixes it, otherwise there isn't much that I can do.

**Comment by Dylan3304** [comment]
@DaneEveritt Okay, using a third party SSL. Still shows offline and won't let me add subdomain.

**Comment by Dylan3304** [comment]
@DaneEveritt anyway to bypass SSL completely?

**Comment by DaneEveritt** [comment]
Nope, no way to disable SSL. I've honestly never seen that error before, and it doesn't make sense to me why it is being thrown. Are you absolutely positive that you have configured the certificates correctly (i.e. browsing to https://domain:5656 doesn't display any notifications about SSL)?

**Comment by Dylan3304** [comment]
I completely bypassed something. I get prompted with not trusted cert. See for your self (https://s1.minewrath.com:5656)

**Comment by DaneEveritt** [comment]
You are still using a self-signed certificate.

**Comment by Dylan3304** [comment]
Is that a problem? Does it need to be verified by someone else?

**Comment by DaneEveritt** [comment]
Like I said earlier in the conversation, self-signed certificates are notoriously problematic. Please get a signed certificate from StartSSL (they are free, and work) and set that up for Scales.

**Comment by Dylan3304** [comment]
@DaneEveritt could I use a CloudFlare free trusted ssl?

**Comment by DaneEveritt** [comment]
Yeah, that should work too.

**Comment by DaneEveritt** [comment]
@Dylan3304 — No. CloudFlare SSL is through the website itself, and handled by them, Scales needs raw access to the certificates.

**Comment by Dylan3304** [comment]
@DaneEveritt You'll never guess what happened! My StartSSL was declined.

**Comment by DaneEveritt** [comment]
You can try https://ssl.comodo.com/free-ssl-certificate.php

**Comment by Dylan3304** [comment]
@DaneEveritt just bought a positive SSL. Hope this works!

**Comment by DaneEveritt** [comment]
It should, just make sure you get it configured correctly in Scales. When you visit https://s1.minewrath.com:5656 it should show as a signed certificate when you view the info (by clicking the little https/lock icon).

**Comment by Dylan3304** [comment]
@DaneEveritt, I've got my files from Namecheap (Like 3 certs). Which ones to I install for PP? The root CA, the domain verfication? I'm confused.

**Comment by DaneEveritt** [comment]
There should be a file called `domainname.crt` and you should have one on your server somewhere named `domainname.key`. Put both of those files in the base scales directory, and edit `config.json` to look for those.

Also, do a `git pull` on Scales since I just fixed a little bug.

**Comment by Dylan3304** [comment]
@DaneEveritt I've install the certificate, everything seems valid in the browser like you said. However, node is still offline. :(

**Comment by Dylan3304** [comment]
@DaneEveritt I installed the SSL like you said, and it shows up valid in the browser. However, the node still shows up `offline`. I'm running Ubunutu 14.04 LTS, if that is any help.

**Comment by Dylan3304** [comment]
@DaneEveritt, if you want future access to my server, shoot me an email to the address in my GitHub account. I'd really like some input here...

**Comment by DaneEveritt** [comment]
(you don't need to tag my name every time on this, I receive notifications for everything in these repos)

Anyways, what is being thrown into the PufferPanel logs, can you provide those again? This is a really strange issue, and I cannot reproduce it anywhere. Lets see what the PufferPanel logs say.

**Comment by Dylan3304** [comment]
**Exception Log:**
[2015-04-29 20-05-28] Klein\Exceptions\UnhandledException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/klein/klein/src/Klein/Klein.php:925 caused by PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/j4mie/idiorm/idiorm.php:429  @  http://cp.minewrath.com/admin/node/view/1/settings  @@  exception-2015-04-29-20-05-28-64274d4ac3bc16ee6ddd4c32099ee94c.html
[2015-04-29 20-05-33] Klein\Exceptions\UnhandledException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/klein/klein/src/Klein/Klein.php:925 caused by PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node' in 'field list' in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/j4mie/idiorm/idiorm.php:429  @  http://cp.minewrath.com/admin/node/view/1/settings  @@  exception-2015-04-29-20-05-28-64274d4ac3bc16ee6ddd4c32099ee94c.html

**Info Log:**
[2015-04-29 20-24-34] Exception: Peer's certificate issuer has been marked as not trusted by the user. in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/mashape/unirest-php/src/Unirest/Request.php:427  @  http://cp.minewrath.com/admin/server/new  @@  exception-2015-04-29-20-24-34-0b00e688b4c923ba69c00b2a891e0265.html
[2015-04-30 06-17-31] Exception: Could not resolve host: s1.minewrath.com; Name or service not known in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/mashape/unirest-php/src/Unirest/Request.php:427  @  http://cp.minewrath.com/admin/server/new  @@  exception-2015-04-30-06-17-31-fff4e56fee00084829b43145941df7aa.html
[2015-04-30 17-03-00] Exception: Peer's Certificate issuer is not recognized. in /var/sentora/hostdata/dseidt/public_html/cp_minewrath_com/vendor/mashape/unirest-php/src/Unirest/Request.php:427  @  http://cp.minewrath.com/admin/server/new  @@  exception-2015-04-30-17-03-00-9ab5271984c641f6f013ce4d4c977843.html

Some of these are old, and the ssl works fine if you visit https://s1.minewrath.com.

**Comment by DaneEveritt** [comment]
It almost looks like PHP isn't accepting your certificate, let me try something on my end real quick.

**Comment by DaneEveritt** [comment]
Ok, if that doesn't work at all, I think I found a fix. Turns out curl no longer ships with the CA Certificates already, so we need to add them all:

```
cd /etc/php5
curl -O http://curl.haxx.se/ca/cacert.pem
```

Then you need to edit your `php.ini` file, which is probably somewhere in `/etc/php5` (I don't remember exactly where) and add this to the file: `curl.cainfo = "/etc/php5/cacert.pem" `

**Comment by Blackbyte1604** [comment]
Is it possible to trust a self signed certifcate?

**Comment by Dylan3304** [comment]
1. That returned an internal server error.
2. That helped nothing what so ever.

**I'm starting to think the Panel/My VPS is blocking a connection to the node.**
